version: "3"
services:
  inv_app_backend:
    container_name: inv_app_backend
    build:
      context: backend-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=local
    volumes:
      - ./backend-app:/app

  postgres:
    image: postgres:latest
    container_name: inv_app_postgres
    env_file:
      - ./development/.env.secrets
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
