import { Invoice } from "./invoice.interface";

const invoices: Invoice[] = [
  {
    id: 1,
    payee: "Amazon",
    date: "2024-04-15",
    description: "Invoice 1",
    status: "open",
    amount: 100,
  },
  {
    id: 2,
    payee: "Amazon",
    date: "2024-04-16",
    description: "Invoice 2",
    status: "open",
    amount: 200,
  },
  {
    id: 3,
    payee: "Amazon",
    date: "2024-04-17",
    description: "Invoice 3",
    status: "open",
    amount: 150,
  },
  {
    id: 4,
    payee: "Amazon",
    date: "2024-04-15",
    description: "Invoice 1",
    status: "open",
    amount: 100,
  },
  {
    id: 4,
    payee: "Amazon",
    date: "2024-04-15",
    description: "Invoice 1",
    status: "open",
    amount: 100,
  },
  {
    id: 4,
    payee: "Amazon",
    date: "2024-04-15",
    description: "Invoice 1",
    status: "open",
    amount: 100,
  },
  {
    id: 4,
    payee: "Amazon",
    date: "2024-04-15",
    description: "Invoice 1",
    status: "open",
    amount: 100,
  },
  {
    id: 4,
    payee: "Amazon",
    date: "2024-04-15",
    description: "Invoice 1",
    status: "open",
    amount: 100,
  },
  {
    id: 4,
    payee: "Amazon",
    date: "2024-04-15",
    description: "Invoice 1",
    status: "open",
    amount: 100,
  },
  {
    id: 4,
    payee: "Amazon",
    date: "2024-04-15",
    description: "Invoice 1",
    status: "open",
    amount: 100,
  },
  {
    id: 4,
    payee: "Amazon",
    date: "2024-04-15",
    description: "Invoice 1",
    status: "open",
    amount: 100,
  },
  {
    id: 4,
    payee: "Amazon",
    date: "2024-04-15",
    description: "Invoice 1",
    status: "open",
    amount: 100,
  },
  {
    id: 4,
    payee: "Amazon",
    date: "2024-04-15",
    description: "Invoice 1",
    status: "open",
    amount: 100,
  },
  {
    id: 4,
    payee: "Amazon",
    date: "2024-04-15",
    description: "Invoice 1",
    status: "open",
    amount: 100,
  },
  {
    id: 4,
    payee: "Amazon",
    date: "2024-04-15",
    description: "Invoice 1",
    status: "open",
    amount: 100,
  },
  {
    id: 4,
    payee: "Amazon",
    date: "2024-04-15",
    description: "Invoice 1",
    status: "open",
    amount: 100,
  },
  {
    id: 4,
    payee: "Amazon",
    date: "2024-04-15",
    description: "Invoice 1",
    status: "open",
    amount: 100,
  },
  {
    id: 4,
    payee: "Amazon",
    date: "2024-04-15",
    description: "Invoice 1",
    status: "open",
    amount: 100,
  },
  {
    id: 4,
    payee: "Amazon",
    date: "2024-04-15",
    description: "Invoice 1",
    status: "open",
    amount: 100,
  },
  {
    id: 4,
    payee: "Amazon",
    date: "2024-04-15",
    description: "Invoice 1",
    status: "open",
    amount: 100,
  },
  {
    id: 4,
    payee: "Amazon",
    date: "2024-04-15",
    description: "Invoice 1",
    status: "open",
    amount: 100,
  },
];

export default invoices;
